<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="Manu" failures="1" tests="5" name="Test" time="53.983" errors="0" timestamp="2022-08-23T14:45:38 IST">
  <testcase classname="com.Buildvest.Staff.StaffTestng" name="verifyAccountInApprovePendingAccountTest" time="7.989"/>
  <testcase classname="com.Buildvest.Customer.FirsttestNg" name="addBenificiaryYourselfTest" time="3.369"/>
  <testcase classname="com.Buildvest.Customer.FirsttestNg" name="ToVerifyCustomerAddBeneficiarythengotoFundTransferPageLogoutApplicationTest" time="3.394">
    <failure type="java.lang.AssertionError" message="we fail testcase 3">
      <![CDATA[java.lang.AssertionError: we fail testcase 3
at com.Buildvest.Customer.FirsttestNg.ToVerifyCustomerAddBeneficiarythengotoFundTransferPageLogoutApplicationTest(FirsttestNg.java:147)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 28 stack frames]]>
    </failure>
  </testcase> <!-- ToVerifyCustomerAddBeneficiarythengotoFundTransferPageLogoutApplicationTest -->
  <testcase classname="com.Buildvest.Customer.FirsttestNg" name="ViewBenificiaryAferAddingBenificiaryTest" time="2.305"/>
  <testcase classname="com.Buildvest.Customer.FirsttestNg" name="ChangePasswordAndLoginWithNewPassword" time="1.856"/>
</testsuite> <!-- Test -->
